### ISSUE TITLE
iOS Doesn't Compile for 0.4.0

### ISSUE THREAD

**Issue by JosephValle** [DenisovAV/flutter_gemma#26]
Hi, thank you for all of your work on this! It seems that the iOS code is missing a comma, not letting it compile. I will edit this shortly with the error message.

**Comment by JosephValle** [comment]
There is just a comma that needs to be removed

**Comment by DenisovAV** [comment]
Thank you, fixed

**Comment by JosephValle** [comment]
Great thanks!
