### ISSUE TITLE
Do you think we can implement retrieval augmented generation for images etc to attach to responses?

### ISSUE THREAD

**Issue by Jamie123234** [DenisovAV/flutter_gemma#30]
The Gemini API is currently experiencing major overloaded errors on its models, but having a local one would be the perfect solution for stability. However, I use the API for document processing. Does this package support RAG? If not, is it possible to implement it?

**Comment by DenisovAV** [comment]
Now, there is no RAG support OOB yet, but you can do it in your project. Just take additional info from somewhere and provide it to the local model
