### ISSUE TITLE
Putting model inside output_path folder does not work

### ISSUE THREAD

**Issue by AliAkberAakash** [DenisovAV/flutter_gemma#6]
I have been trying to run the example app and I was getting the error that the `model.bin` file is not found in `/data/local/tmp/llm/`. It's because I had put the model inside the `output_path` folder. Pushing just the `model.bin` in the device is working for me. In the `Readme` the instructions are to have the `model.bin` file inside `output_path` folder. So maybe we can update the `Readme`? 

Device Used: Samsung Galaxy A52s
Platform: Android

**Comment by DenisovAV** [comment]
Yep, looks like there is mistke, will fix it today, thank you for highlighting

**Comment by IldySilva** [comment]
@AliAkberAakash  pls, i'm getting the same error
could you please explain better what you've done??

**Comment by DenisovAV** [comment]
I updated the manual, sorry for the delay, please take a look
