### ISSUE TITLE
Model to assets folder

### ISSUE THREAD

**Issue by Bondigame-personal** [DenisovAV/flutter_gemma#7]
Hello.
Can I use model from flutter assets folder?

**Comment by Bondigame-personal** [comment]
Got it. You can put the model in assets and specify the path in the plugin.

**Comment by DenisovAV** [comment]
You shouldn't put the model in assets, in this case the size of app will be too big

**Comment by tempo-riz** [comment]
how did you do that @Bondigame-personal  ? at least for testing purpose :)
