### ISSUE TITLE
Download model feature

### ISSUE THREAD

**Issue by tempo-riz** [DenisovAV/flutter_gemma#8]
Hey @DenisovAV first thanks for this package !

How are you planning to implement the download model feature ? Do you need any help or contribution ?

**Comment by DenisovAV** [comment]
Yes, this is the first thing I am going to implement: the ability to specify the model path and download it in the background. I hope to get around to it soon. However, if you want to help, I would gladly accept your assistance to get it done faster :)

**Comment by tempo-riz** [comment]
The thing I noticed is to download the model you must be login and accept the google terms, and you are probably rate limited, which could be problematic in a production app, maybe the model is also freely hosted somewhere we could use ? I didn't find yet

**Comment by DenisovAV** [comment]
please check 0.3.0 version, probably there is functionality you looked for
